import localFont from "next/font/local";
import "./globals.css";

const Yekan = localFont({
  src: [
    {
      path: "../../public/fonts/Yekan.ttf",
      weight:"300",
    },
  ],
  variable:"--font-yek"
});

const YekanBold = localFont({
  src: [
    {
      path: "../../public/fonts/BYekan+ Bold.ttf",
      weight:"900",
    },
  ],
  variable:"--font-yek-bold"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Yekan.variable} ${YekanBold.variable} `}>{children}</body>
    </html>
  );
}
